{{- /*
Copyright (c) 2025 Fraunhofer Institute for Energy Economics and Energy System Technology (IEE)

This program and the accompanying materials are made available under the
terms of the Apache License, Version 2.0 which is available at
https://www.apache.org/licenses/LICENSE-2.0

SPDX-License-Identifier: Apache-2.0

Contributors:
     Fraunhofer IEE - initial API and implementation

*/}}

{{- if and (.Values.ui.enabled) (.Values.ui.ingress.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui
  namespace: {{ include "common.namespace" . | quote }}
  labels: {{- include "ui.labels" . | nindent 4 }}
  {{- if .Values.ui.ingress.tls.enabled }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ui.ingress.tls.issuer }}
  {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.controlplane.ingress.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ui
                port:
                  name: frontend
  {{- if .Values.ui.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.controlplane.ingress.host }}
      secretName: {{ .Values.controlplane.ingress.host }}-tls
  {{- end }}
{{- end }}