#
#  Copyright (c) 2025 Fraunhofer Institute for Energy Economics and Energy System Technology (IEE)
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#       Fraunhofer IEE - initial API and implementation
#
#

name: dena-connector-local-dev

volumes:
  vault_data:
  postgres_data:

services:
  vault:
    container_name: vault
    image: hashicorp/vault:1.18.1
    command: [ "vault", "server", "-config=/vault/config" ]
    ports:
      - "8200:8200"
    environment:
      VAULT_API_ADDR: http://127.0.0.1:8200
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_DEV_ROOT_TOKEN_ID: devpass
      VAULT_LOCAL_CONFIG: '{"storage": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
      VAULT_SUPPLEMENTAL_CONFIG: '{"ui": false, "listener": [{"tcp": { "address": "0.0.0.0:8200", "tls_disable": true}}]}'
      SIGNER_KEY: |
        -----BEGIN PRIVATE KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDb1+hXTJU8LVHK
        OkKUer6lUAE4aGwIidWAgkVn7L6WSuy8fYE/T0XAP9MnKRS/R2w4WR0rfQ3tRqXk
        +/v0YvQcIho1Fa7A2HlXdm7E1Ky8HrksRxkfZKOnyRNQULQZaRaIf619SaBD9il3
        V/jkS1jcPBF6MuUOr42ilK82+3wCc+ltocLGAL1gIVFoPakulW0sn5EpxWIiKDm+
        uX47GmME73mObxKAm4hC+6k5LUuiL9lMBdtUw66mLU9jBdDRd4MVWrSZ8kR9Ng61
        2Tt0Qigsxfjr+O7WR+qBy6BIaqjU/uTq67Uf+PYaGJHjWvsK/KeI/qsSZxhKgxlm
        +q9bVdPhAgMBAAECggEABlcJqkrZGu0rqKtZdDK+AMJ35oqMYwqmj5gyLDcVn/v1
        K9Jqwcqldk/g5QY4RPPoWQ+o2bI3jpo0+o+RypB3/b+2BcXkTkdv6GfP9fk0KhCw
        wmgif1dFqPcRiYVqTDlNnw4fkLdo2czlkT2GPf82RtOspVuGY5AIg6HKE8nY37Eu
        X2MpwSbfTrQCVYklB9mIZal7YBawd4HKJLHth0w+s9fBiMsJw/vAVquXTUa32wnt
        YWn3sQ8al9A+7iXgcuzWe69el2P0nRddsnP1Xx8Dbl6x7dUpFoCL68xJUzB6unqI
        EU9T9gMhrR09cOTvAHwoLu3wG0fNxWmv9qJEB3hOqQKBgQD1I6pTIJIQxkypJpso
        x7MQ5yTZIA1PPC0jUkiGRVFVzQ62y4g4br3ylmENgQcYdjtU2nsPQkZ2Q1VSM2Rj
        hMtAR8DpzzKvYWgVizDVtUC98S7d0O61EohxfSCYuSmy3mfWWo2DTblv/7X717k4
        +zgVuVCSHe37QQfnU9D3pxdiowKBgQDllVboshRnCYiqNt6QhWtm8g8IAvATJIYb
        O/DNiKTARVxgFF1uHQmymnaVGauZmshNz6Hx2+47gzzvC8M1YrZdR8vfAaq4/xeN
        Gi35gtBOrz9LQRbVTn97rjkZgoxIL9mfyZwO9vFGrea1uPTwMXkrQ5vOkECft3jX
        jQlkCC1bqwKBgFsM8jiKAnbEkLjLJBpTgkkm8WLMKuVhPoq+Bz4IBRvPXEW8902u
        pFK0VDwFzrLhR0xPEiIqxa0reUdc206zhiLMA/VUBklp7pUB7BOUjQV/zZ6J+f+7
        cH5msXLIY5qSTRMq8yDv/45/9gIisCNf/Ablm+2JvFj0YJElappxr5ftAoGBAKcq
        ORDP8akguQDvWNk0PILFx4oW0YWut3MHDwwo7YUOO/e9fFYcEJ6ad7OS8G601BpM
        D+fSMsHkii6oiufJS23aRCjJxuxS2WwlXspppJFWayi5aQ3BzXNZ5Tuc4dYB+Vyu
        aNJAnmfPYch5tudZrpeA7+bVBCkHZ5bTm73ZcmVnAoGBAJuxYy49UTQ+w5yRn8wJ
        MHCfd7MQB2C85Ir/0M1j6yMWPgxJXKdOB2K1pBbMRHgGqcSv4a6pJ2D3IDDqOOHG
        369gyJW7qCS3eIn57LrwmO+JET/ypqi+JIWcMMmw6+E2At3nqFBkpes5AspEPtnz
        1VUlpL3Zn5WnA/3vz5R6dWhe
        -----END PRIVATE KEY-----
      VERIFIER_KEY: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA29foV0yVPC1RyjpClHq+
        pVABOGhsCInVgIJFZ+y+lkrsvH2BP09FwD/TJykUv0dsOFkdK30N7Ual5Pv79GL0
        HCIaNRWuwNh5V3ZuxNSsvB65LEcZH2Sjp8kTUFC0GWkWiH+tfUmgQ/Ypd1f45EtY
        3DwRejLlDq+NopSvNvt8AnPpbaHCxgC9YCFRaD2pLpVtLJ+RKcViIig5vrl+Oxpj
        BO95jm8SgJuIQvupOS1Loi/ZTAXbVMOupi1PYwXQ0XeDFVq0mfJEfTYOtdk7dEIo
        LMX46/ju1kfqgcugSGqo1P7k6uu1H/j2GhiR41r7CvyniP6rEmcYSoMZZvqvW1XT
        4QIDAQAB
        -----END PUBLIC KEY-----
    cap_add:
      - IPC_LOCK
    volumes:
      - "../resources/vault-init.sh:/scripts/vault-init.sh"
      - "../resources/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh"
      - type: volume
        source: vault_data
        target: /vault/file
        volume:
          subpath: file
      - type: volume
        source: vault_data
        target: /vault/unseal
        volume:
          subpath: unseal

  postgresql:
    image: bitnamilegacy/postgresql:17.2.0
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_DATABASE: edc
      POSTGRESQL_USERNAME: edc
      POSTGRESQL_PASSWORD: devpass
    volumes:
      - "postgres_data:/bitnami/postgresql"
      - "../resources/membership-attestation.sql:/docker-entrypoint-initdb.d/membership-attestation.sql"
