#
#  Copyright (c) 2025 Fraunhofer Institute for Energy Economics and Energy System Technology (IEE)
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#       Fraunhofer IEE - initial API and implementation
#
#

edc.participant.id=did:web:localhost%3A10085:tester
edc.component.id=tester-connector
edc.hostname=localhost

edc.iam.issuer.id=did:web:localhost%3A10085:tester
edc.iam.did.web.use.https=false
edc.iam.sts.oauth.token.url=http://localhost:10083/api/sts/token
edc.iam.sts.oauth.client.id=did:web:localhost%3A10085:tester
edc.iam.sts.oauth.client.secret.alias=tester-sts-client-secret
edc.iam.credential.revocation.mimetype=application/json

edc.iam.trusted-issuer.0.id=did:web:localhost%3A20085:issuer

edc.vault.hashicorp.url=http://localhost:8200
edc.vault.hashicorp.token=devpass

edc.policy.monitor.state-machine.iteration-wait-millis=30000

web.http.path=/api
web.http.port=9080
web.http.management.path=/api/management
web.http.management.port=9081
web.http.management.auth.type=tokenbased
web.http.management.auth.key=devpass
web.http.control.path=/api/control
web.http.control.port=9082
web.http.protocol.path=/api/v1/dsp
web.http.protocol.port=9083
web.http.version.path=/api/version
web.http.version.port=9085
web.http.catalog.path=/api/catalog
web.http.catalog.port=9086

edc.sql.schema.autocreate=true
edc.datasource.default.user=edc
edc.datasource.default.password=devpass
edc.datasource.default.url=jdbc:postgresql://localhost:5432/edc

edc.catalog.registry.url=http://localhost:3000/api/registry
edc.catalog.registry.api.key=devpass
edc.catalog.cache.execution.period.seconds=30
edc.catalog.cache.execution.delay.seconds=5
edc.catalog.cache.partition.num.crawlers=5

edc.registration.connector.name=tester
edc.registration.registry.url=http://localhost:3000/api/registry
edc.registration.registry.api.key=devpass
edc.registration.keys.name.overwrite=tester
edc.registration.ih.identity.url=http://localhost:10082/api/identity
edc.registration.ih.credentials.url=http://localhost:10081/api/credentials
edc.registration.issuer.did=did:web:localhost%3A20085:issuer

edc.policy.pm.url=https://api-nprd.traxes.io/prprd/forwatt/v2
edc.policy.pm.token.url=https://acc.signin.energy/am/oauth2/realms/root/realms/difesp/access_token
edc.policy.pm.token.client.id=esp_FraunhoferPermissionCZ1MsY_001
edc.policy.pm.token.client.secret.alias=pm-secret